name: TPE Lint & Build
run-name: Lint & Build 
on: [push]
jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - run: make lint
  Build-Engine:
    runs-on: ubuntu-latest
    steps:
      - run: make build
  Build-Sample-Plugins:
    runs-on: ubuntu-latest
    steps:
      - run: make build-plugins
